"""add corrections and message reply link

Revision ID: 9ba16f575a07
Revises: 33b5d3751464
Create Date: 2026-10-09 15:12:28.721090

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9ba16f575a07"
down_revision: str | Sequence[str] | None = "33b5d3751464"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "corrections",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("message_id", sa.Integer(), nullable=False),
        sa.Column("category", sa.String(length=20), nullable=False),
        sa.Column("original_span", sa.Text(), nullable=False),
        sa.Column("corrected_text", sa.Text(), nullable=False),
        sa.Column("explanation_vi", sa.Text(), nullable=False),
        sa.Column("prompt_version", sa.String(length=50), nullable=False),
        sa.CheckConstraint(
            "category IN ('grammar', 'word_choice', 'spelling', 'naturalness')",
            name=op.f("ck_corrections_category"),
        ),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["messages.id"],
            name=op.f("fk_corrections_message_id_messages"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_corrections")),
    )
    op.create_index(
        op.f("ix_corrections_message_id"), "corrections", ["message_id"], unique=False
    )
    op.add_column(
        "messages", sa.Column("reply_to_message_id", sa.Integer(), nullable=True)
    )
    op.create_unique_constraint(
        op.f("uq_messages_reply_to_message_id"), "messages", ["reply_to_message_id"]
    )
    op.create_foreign_key(
        op.f("fk_messages_reply_to_message_id_messages"),
        "messages",
        "messages",
        ["reply_to_message_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_messages_reply_to_message_id_messages"), "messages", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("uq_messages_reply_to_message_id"), "messages", type_="unique"
    )
    op.drop_column("messages", "reply_to_message_id")
    op.drop_index(op.f("ix_corrections_message_id"), table_name="corrections")
    op.drop_table("corrections")
    # ### end Alembic commands ###
